services:
  app:
    image: webkul/bagisto:2.2.2
    platform: linux/amd64
    container_name: bagisto_app
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
    environment:
      - APP_ENV=local
      - DB_HOST=db
      - DB_DATABASE=bagisto
      - DB_USERNAME=bagisto
      - DB_PASSWORD=bagisto
    depends_on:
      - db

  db:
    image: mysql:5.7
    platform: linux/amd64
    container_name: bagisto_db
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: bagisto
      MYSQL_USER: bagisto
      MYSQL_PASSWORD: bagisto
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata: